### ISSUE TITLE
could not build objective-c module gtm_oauth2

### ISSUE THREAD

**Issue by JoeShi** [google/gtm-oauth2#47]
iOS: 9.1

It says the error: "GTMHTTPFetcher.h" file not found. 

However, since it is not supported, it should use GTMSessionFetcher.h instead. But when I use cocoapods, it does not work.

**Comment by JoeShi** [comment]
create a brand new project and use cocoapods to import the "gtm-oauth2". then this error shows up

**Comment by sleroux** [comment]
Having the same issue here as well. The GTMHTTPFetcher dependency isn't part of the tree so the static lib can't be built. Also, since the latest Xcode uses the iOS 9 as it's base SDK, this project should be using GTMSessionFetcher instead (I assume) since GTMHTTPFetcher isn't supported for iOS 9. Are there any plans to be able to build the framework/static lib using Xcode 7.1 and adding the required dependencies to the tree?

**Comment by thomasvl** [comment]
Not sure what podspec you were using, but we've now got an official one in in the repo, that should be working.
