### ISSUE TITLE
How to Login with hardcode username/pass?

### ISSUE THREAD

**Issue by anhhtbk** [google/gtm-oauth2#68]

**Comment by thomasvl** [comment]
Generally speaking clients don't do this.  As it is possible for someone to inspect the binary and extract the username and password from the binary.  What is it you are trying to do?

**Comment by anhhtbk** [comment]
I am trying create app what user can use to upload video to YouTube (and get link to share) without login google.

**Comment by thomasvl** [comment]
Generally speaking, you can't record a username/password like this client side because when the server sees this many logins, it will invoke a challenge for ensure it isn't a bot and/or confirm the account isn't being hacked because of multiple parallel logins.   To really use a single account, you'd like have to have your own server that did the final uploads.  I'd suggest checking the YouTube docs and support areas in general for how to go about doing something like this, as using one account for different user upload seems like something they wouldn't normally want.
